### ISSUE TITLE
再次请教，游泳项时间统计显示好像不对

### ISSUE THREAD

**Issue by koobai** [ben-29/workouts_page#10]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/50470569/230578998-26b56537-0848-46ef-971d-567be2442e82.png">
这里增加的是1个多小时，但实际页面显示，只是53分钟
<img width="2149" alt="image" src="https://user-images.githubusercontent.com/50470569/230579195-4c71c60e-e8b1-485d-a0e2-2679331c975e.png">

就连同一个时间，数据也是一样的，但显示时间也不同
<img width="572" alt="image" src="https://user-images.githubusercontent.com/50470569/230579544-400deed9-f4dc-4298-84a7-1da73d821c34.png">

问题不大，只是发现了，所以请教下，哈哈，感谢～

这是个人数据页，https://workouts.koobai.com

**Comment by ben-29** [comment]
看了下代码，这个时间没有用 `moving_time`, 而是用 `距离/平均速度` 导致了有差异，等我有空改成直接用 `moving_time`吧

**Comment by koobai** [comment]
辛苦，等着修复～

**Comment by ben-29** [comment]
时间问题改了，参考最新的提交。

配速的问题，我这边游泳的显示的都是对的。
可能跟设备有关，你是用什么设备记录，用哪个平台同步的，那个平台显示数据正常吗？配速是每1000米用时，可能要转换下，有具体数据可以分析下吗？

**Comment by koobai** [comment]
感谢，已更改。
关于配速：我是用苹果watch同步到strava的。刚用chatgpt换算了，可能是对的，他每次的结果不大一样。
这是最近几次的strava数据:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/50470569/231793348-039d19c1-5a72-45a6-a6ea-0e4fdac1efbe.png">
<img width="348" alt="image" src="https://user-images.githubusercontent.com/50470569/231793414-f101d32c-b02b-48d0-844c-9d90e2d8efd1.png">
<img width="461" alt="image" src="https://user-images.githubusercontent.com/50470569/231793455-0d1cd08a-e16b-48fc-9fb3-9a45a8e35113.png">

这是生成之后显示的数据：
<img width="583" alt="image" src="https://user-images.githubusercontent.com/50470569/231793587-712ef757-5fa8-4dad-90aa-ef96f5cda06e.png">

现在只是在学习游泳
