### ISSUE TITLE
继续请教，看你的地图不会显示详细的街道，应该怎么设置

### ISSUE THREAD

**Issue by koobai** [ben-29/workouts_page#11]
继续请教，看你的地图不会显示详细的街道，是不是在Strava软件设置？或者直接在 mapbox里设置？具体能分享下方法么，感谢～

**Comment by ben-29** [comment]
https://github.com/ben-29/workouts_page/blob/b78fbc8179c8da1c93b8ba81e8c7abef6b717aa6/src/utils/const.js#L25
这里改成 `false` 即可
