### ISSUE TITLE
自定义的运动名称是如何实现的？

### ISSUE THREAD

**Issue by aimdotsh** [ben-29/workouts_page#13]
<img width="440" alt="image" src="https://github.com/ben-29/workouts_page/assets/27554033/dcff0b0e-c202-4b9d-8439-4c9ff89591b1">
我刚下载了https://github.com/ben-29/workouts_page 在本地部署了，没搞明白自定义的名称是如何实现的

**Comment by ben-29** [comment]
有两种情况可以改名称:
1. 如果你使用的是Garmin/strava, 直接在app上面修改运动名称，再执行同步脚本同步
2. 否则，要想修改，可以手动打开sqlite文件: `scripts/data.db`, 找到你想修改的记录，修改 `name`字段，修改完后，执行任意一种同步脚本同步即可

**Comment by aimdotsh** [comment]
哦哦，我试了下用郁金香的修改名称的功能，目测没生效哈，我测试下第二个方式。多谢。

**Comment by aimdotsh** [comment]
通过修改sqlite 文件实现了。多谢
