### ISSUE TITLE
手机浏览跑步数据和地图会一起移动

### ISSUE THREAD

**Issue by aimdotsh** [ben-29/workouts_page#15]
<img width="422" alt="image" src="https://github.com/ben-29/workouts_page/assets/27554033/75d2488b-8203-4be3-8844-79960d7bc118">

在手机浏览器上，会出现如上，我查看跑步数据的左右移动的时候，地图也会左右移动然后出现一块空白。
不知道是否可以实现跟  yihong0618 的原版本那样，跑步数据左云移动，地图是不移动的，地图正好居中。

<img width="430" alt="image" src="https://github.com/ben-29/workouts_page/assets/27554033/75d3d950-a9aa-490e-9cc7-33569f162685">

**Comment by ben-29** [comment]
好的，等我有空同步下上游代码

**Comment by ben-29** [comment]
@aimdotsh 修复了，同步最新代码试试

**Comment by aimdotsh** [comment]
这么速度，晚会就试下。

**Comment by aimdotsh** [comment]
感谢，完美解决，total 页也完美适配了。太给力。
