### ISSUE TITLE
选择单条记录地图显示的路径不正确

### ISSUE THREAD

**Issue by Coder-ZJQ** [ben-29/workouts_page#17]
导入 strava 同步的 zwift 骑行纪录，网页上选择单条纪录时（列表选择和 svg 选择），地图显示的路径不正确，只有前几条会有这种问题。

### 列表选择
选择的记录是 `Zwift - Race: Stage 1: Race the Worlds—Rolling Highlands (C) on Rolling Highlands in Scotland` （红色选中那条）地图上显示的却是上一条 `Zwift - Volcano Circuit in Watopia`
<img width="600" alt="image" src="https://github.com/ben-29/workouts_page/assets/15013685/f1179818-9f01-4b29-9901-b5bfdba51072">

### total 选项卡 svg 选择
在 total 选项卡通过 svg 路径缩略图选择，svg 选择的是 `2023-08-02 14.9km` 的路径缩略图，地图显示的却是上一条 `2023-08-02 22.72km`：
<img width="600" alt="image" src="https://github.com/ben-29/workouts_page/assets/15013685/fe5be85e-541f-46fe-ab8b-d15516264529">

（另外生成的 svg 路径缩略图是正确的）

### 其它
- 我的网页：[https://workouts.jqz3.tech/](https://workouts.jqz3.tech/)
- 我的仓库：[https://github.com/Coder-ZJQ/workouts_page](https://github.com/Coder-ZJQ/workouts_page)

**Comment by ben-29** [comment]
已定位到问题，同一天有多条运动记录时有问题。等有空了再修复

**Comment by Coder-ZJQ** [comment]
> 已定位到问题，同一天有多条运动记录时有问题。等有空了再修复

我试着提了条 PR，可以看下有没问题。
[https://github.com/ben-29/workouts_page/pull/18](https://github.com/ben-29/workouts_page/pull/18)
