### ISSUE TITLE
跑步以外的数据如何同步

### ISSUE THREAD

**Issue by wancheng** [ben-29/workouts_page#2]

**Comment by ben-29** [comment]
你用的是什么平台？参考：https://github.com/yihong0618/running_page/blob/master/README-CN.md#%E6%94%AF%E6%8C%81

**Comment by arthurfsy2** [comment]
想请教一下KEEP现在的其他类型运动：户外行走、登山等这些，可以通过keep_sync.py获取吗？
目前看到有下面的API，然后尝试过改成`&type=all`或者去掉`&type=running`，不过好像都不生效

`RUN_DATA_API = "https://api.gotokeep.com/pd/v3/stats/detail?dateUnit=all&type=running&lastDate={last_date}"`
