### ISSUE TITLE
香港、澳门的数据如何才能正确显示？

### ISSUE THREAD

**Issue by Jeffggmm** [ben-29/workouts_page#21]
录入了港澳各一条GPX数据，地理显示如下：大網仔路 Tai Mong Tsai Road, 北潭涌 Pak Tam Chung, 西貢區 Sai Kung District, 新界 New Territories, 香港 Hong Kong。  更改为 香港,中国或, 香港特别行政区, 中国 在汇总数据里都没有，请问如何处理？

**Comment by ben-29** [comment]
更新最新代码，地址最后改为:
``` 香港特别行政区, 中国 ```

**Comment by Jeffggmm** [comment]
收到多谢
