### ISSUE TITLE
希望右侧地图功能按钮再增加3个

### ISSUE THREAD

**Issue by Jeffggmm** [ben-29/workouts_page#22]
有了右侧的这个最大化按钮方便了不少，希望将来还能增加3个按钮。 1：缩放适合中国地图轮廓图按钮，只有中国轮廓图出来后，才能显示多少省份，多少城市，没有按钮需要用鼠标滚轮或手指缩放好久:2：其他两个希望是 缩放的 +  -  按钮，

如果再增加一个 关灯 按钮更好，就是把地图背景变成全黑，强化显示 运动轨迹的星星点点

![搜狗截图20231013215132](https://github.com/ben-29/workouts_page/assets/118322305/69f40c9a-dbfa-4e64-80d3-ff2a7cf3ce6c)

**Comment by ben-29** [comment]
好，已记录，考虑以后实现

**Comment by ben-29** [comment]
@Jeffggmm 增加了缩放按钮

![image](https://github.com/ben-29/workouts_page/assets/6956444/b51cb094-cf96-419d-8842-178238ac5d0b)

**Comment by ben-29** [comment]
已添加 关灯效果
![image](https://github.com/ben-29/workouts_page/assets/6956444/38b350db-278e-4ad9-9eda-d62798506dd4)
