### ISSUE TITLE
yihong的running page版本的马拉松 能否增加下？

### ISSUE THREAD

**Issue by Jeffggmm** [ben-29/workouts_page#23]
yihong的running page 有个早午晚跑步，半马和马拉松的汇总，workout page好像是取消了，能否把马拉松的选项回复，希望借此来展示下跑过的全马，半马是否显示都无所谓，反正不算数，平时LSD也经常刷21K.马拉松如果像GARMIN赛段那样有个小图标就更好了。

参看图1 图2，多谢

![11](https://github.com/ben-29/workouts_page/assets/118322305/0add56e0-05a1-4a39-b7c6-4ea47e1a02c2)
![22](https://github.com/ben-29/workouts_page/assets/118322305/8eebd172-a63a-4233-b064-7bdafb349c16)

**Comment by ben-29** [comment]
已添加
