### ISSUE TITLE
Garmin数据同步出错

### ISSUE THREAD

**Issue by wancheng** [ben-29/workouts_page#3]
Syncing Activity IDs
5 new activities to be downloaded
Download finished. Elapsed 0.5743858814239502 seconds
38
Something went wrong when loading GPX. for file 9223370494458586307.gpx, we just ignore this file and continue
Something went wrong when loading GPX. for file 9223370387517129230.gpx, we just ignore this file and continue
descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'NoneType' object
descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'NoneType' object
Something went wrong when loading GPX. for file 9223370383542488249.gpx, we just ignore this file and continue
descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'NoneType' object
Something went wrong when loading GPX. for file 9223370510136908807.gpx, we just ignore this file and continue
descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'NoneType' object
Something went wrong when loading GPX. for file 9223370383334169725.gpx, we just ignore this file and continue
descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'NoneType' object
Something went wrong when loading GPX. for file 9223370499078271307.gpx, we just ignore this file and continue
descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'NoneType' object
Something went wrong when loading GPX. for file 9223370509821819807.gpx, we just ignore this file and continue
descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'NoneType' object
Something went wrong when loading GPX. for file 193645433.gpx, we just ignore this file and continue
descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'NoneType' object
load 29 tracks
..........................+++%

**Comment by wancheng** [comment]
看了一下gpx文件，是一个呼吸训练相关的数据。

**Comment by wancheng** [comment]
其他几个是上次同步Keep时出现了空数据。

**Comment by ben-29** [comment]
这几个文件都是有轨迹的文件吗？能否发个有gps轨迹点的文件看看

**Comment by wancheng** [comment]
我检查了一下，没有轨迹，可以关闭了。
