### ISSUE TITLE
位置统计问题

### ISSUE THREAD

**Issue by SongJgit** [ben-29/workouts_page#31]
突然发现缩放地图之后，仅仅显示了部分数据。
![微信图片_20240410081653](https://github.com/ben-29/workouts_page/assets/30189040/40fc16f9-8d33-40e0-b7ba-d6587814b6c2)

查看activities.json之后发现，是strava同步下来的很多数据都没有位置信息，仅仅有一个China，应该是这个导致的数据缺失，这是为什么呢。
类似于下面这样，这些运动数据都是garmin直接同步到strava中的。
"distance": 35823.7,
"moving_time": "1:10:30",
"type": "Ride",
"start_date": "2023-08-06 12:29:01+00:00",
"start_date_local": "2023-08-06 20:29:01",
"location_country": "China",

**Comment by ben-29** [comment]
我也是 garmin 直接同步到 strava, 再通过 strava 同步到 workouts_page 的， GitHub Action 自动跑的, location_country 一直都正常，有省市区。
估计是你环境有问题？

**Comment by SongJgit** [comment]
已经解决了，是墙内问题。 我的第一次同步是本地跑的，所以错误了。
但是我发现了新问题。

![image](https://github.com/ben-29/workouts_page/assets/30189040/679a03a7-6acb-4790-bf04-b2e3b0742515)

**Comment by ben-29** [comment]
最新提交修复了这个问题 @SongJgit
