### ISSUE TITLE
是如何在total里显示国家的

### ISSUE THREAD

**Issue by gavenwan** [ben-29/workouts_page#32]
我用的是running_page，但是国家一直无法涂色显示，请教是改哪里可以在total里显示国家

**Comment by ben-29** [comment]
你给出的信息很少，没有链接也没有截图，很难判断是什么原因。
可以检查一下以下几点：
1. 是否同步了最新的代码
3. total 页面显示的国家数量是多少，如果不大于1，手动打开 data.db, 确认相应记录的 `location_country` 上有相应的 简体中文国家名
4. 部署的是否是最新的代码
