### ISSUE TITLE
行者的骑行数据显示

### ISSUE THREAD

**Issue by vvanglro** [ben-29/workouts_page#33]
你好，行者的骑行数据展示到页面，Date日期好像不对，BPM也没显示

Date日期取的是avtivities.json里的start_date_local时间是错的，start_date这个字段的对应时间是对的

https://www.vvanglro.link/

**Comment by ben-29** [comment]
日期问题已修复，拉最新的代码试试，`imported.json` 和 `run_page/data.db` 删掉，重新跑一次 xingzhe_sync 即可

至于 BPM 是心率，前提是你有用心率带等设备，并且行者里的详情也能看到心率，如果行者确实有心率数据，方便可以发一份 gpx 发我的邮箱，我看看是什么问题

**Comment by vvanglro** [comment]
activities.json 中的数据没有生成, 我自己调用的make_activities_file方法  db和gpx都已经生成过了

<img width="1188" alt="image" src="https://github.com/ben-29/workouts_page/assets/43594924/0d6fcd84-1fcf-43db-b438-2e1881d926db">

**Comment by vvanglro** [comment]
Generator貌似是这个类下的load方法查询出来的activities数据为空    
 ```py   
    def load(self):
        activities = (
            self.session.query(Activity)
            .filter(Activity.distance > 0.1)
            .order_by(Activity.start_date_local)
        )
```

**Comment by vvanglro** [comment]
- -，我把data.db打开看了下，activities这个表数据是空的

**Comment by ben-29** [comment]
项目目录下的 `imported.json` 删掉了吗？

**Comment by vvanglro** [comment]
> 项目目录下的 `imported.json` 删掉了吗？

我的 sry，哈哈哈，刚action完可以了。
