### ISSUE TITLE
百度/高德 数据导出

### ISSUE THREAD

**Issue by maicss** [ben-29/workouts_page#34]
请问可以支持这两个软件轨迹的导出，然后导入到这个应用里？

谢谢，非常棒的应用。

**Comment by ben-29** [comment]
什么轨迹呢？
这个项目主要是关于运动的记录，导航的轨迹不在运动的范围

另外，项目支持导入谷歌地图的kml路书

**Comment by maicss** [comment]
![image](https://github.com/ben-29/workouts_page/assets/9784767/ee4d56fd-0f8d-4753-afdb-a84da816c578)

像是这样的，不知道可不可以。这种数据既有导航也有运动。

**Comment by ben-29** [comment]
目前不支持，不过PR Welcome :)
