### ISSUE TITLE
为什么的运动记录有地点标题，我的只有Run from codoon

### ISSUE THREAD

**Issue by haibuhao** [ben-29/workouts_page#37]

**Comment by haibuhao** [comment]
你是用什么同步方式

**Comment by ben-29** [comment]
运动标题根据不同的方式，有不同的取值
gpx取gpx.trk.name字段
我用 strava 和 garmin。app上可以修改运动标题，同步的时候也会带过来。
你可以看看咕咚上能不能改

**Comment by yihong0618** [comment]
咕咚和其它的目前是写死的，我感觉能同步过来

**Comment by ben-29** [comment]
> 咕咚和其它的目前是写死的，我感觉能同步过来

@yihong0618 装了咕咚 app 看了下，没有运动标题这个字段，也无法修改 😂 写死没毛病

@haibuhao 如果想要能自动同步标题，得使用带 运动标题 的app，如 strava。我看了下咕咚、keep、悦跑圈都没有标题

要手动改也可以，比较麻烦：
 `run_page/data.db` 的 `name` 字段 
或
 `gpx` 的 gpx.trk.name 字段

**Comment by yihong0618** [comment]
好的

**Comment by ben-29** [comment]
@haibuhao 合并了[新功能](https://github.com/yihong0618/running_page/pull/733)，新运动标题为 `城市名+运动类型`， (如`深圳市 跑步`)， 需要的话用最新代码试下
