### ISSUE TITLE
只同步了几条进去

### ISSUE THREAD

**Issue by Zhigang27** [ben-29/workouts_page#5]
昨晚试了一下你修改的这个支持识别骑车的，结果只抓取了几条，之前用yihong0618那个是都抓过来了。执行过程中的提示如下图
![WechatIMG33872](https://user-images.githubusercontent.com/118618521/202886101-a1d772cc-2da9-4534-be6a-ee3ce9f008ce.jpeg)
能指导一下该怎么做吗？谢谢。

**Comment by ben-29** [comment]
第一次同步时，这行代码改成 
[GET_ALL = False](https://github.com/ben-29/workouts_page/blob/3caf8f18235f6a1d591a27f2c57b74276781b932/scripts/garmin_sync.py#L55)
-> `GET_ALL = True` 即可同步所有记录，默认时获取最新20条(定时更新时)
可以在本地改代码，然后运行一下 garmin_sync.py, 如果不行的话删除 `scripts/data.db`再试试

**Comment by Zhigang27** [comment]
搞定！谢谢Ben。我想问一下，之后只同步最新20条是为了节约时间对吗？
另外，我对比我的Garmin传输到郁金香的记录，骑车和跑步的数量好像有一些差距，是不是有功能可以单独导入某条数据？此外，我还在家附近的湖里试过几次桨板（有GPS记录），如何新增类别，调整颜色？谢谢。

**Comment by ben-29** [comment]
> 搞定！谢谢Ben。我想问一下，之后只同步最新20条是为了节约时间对吗？ 

是的，只有第一次初始数据需要获取全量数据，后面只需要同步最新即可

> 另外，我对比我的Garmin传输到郁金香的记录，骑车和跑步的数量好像有一些差距，是不是有功能可以单独导入某条数据？

可以看看控制台输出，是否有些记录没有轨迹，被跳过了，项目只会同步有GPS记录的数据，可以打开`data.db`看看里面的数据是否匹配，没有轨迹的记录应该也在里面。
没有单独导入某条数据功能，可以把gpx文件的放在`GPX_OUT`文件夹，运行`gpx_sync.py`即可导入

> 此外，我还在家附近的湖里试过几次桨板（有GPS记录），如何新增类别，调整颜色？谢谢。

有GPS记录的话，可以参考[文档](https://github.com/ben-29/workouts_page/blob/master/README-CN.md#%E4%B8%80%E4%BA%9B%E4%B8%AA%E6%80%A7%E5%8C%96%E9%80%89%E9%A1%B9) 修改

**Comment by Zhigang27** [comment]
我试着导出了我的几条皮划艇的GPX，搜索里面的Type，确认是叫kayaking，然后按照参考文档修改了，但执行的时候总是出错，试了好半天了。还是找不到原因。只好厚着脸皮请大神帮找找问题。我把相关文件和一条皮划艇的都附带在这里。谢谢，谢谢。

[归档.zip](https://github.com/ben-29/workouts_page/files/10049647/default.zip)

**Comment by ben-29** [comment]
我看了你的仓库，还需要改几个地方：
1、https://github.com/Zhigang27/My-Outdoor-Workouts/blob/22ab3b449356e0a83b61495eee48f6c3d9821e0e/src/utils/const.js#L43 和 https://github.com/Zhigang27/My-Outdoor-Workouts/blob/22ab3b449356e0a83b61495eee48f6c3d9821e0e/src/utils/const.js#L55 加个 `KAYAKING_TITLE`
2、删除 `scripts/data.db` 后重新跑 `Run_data_sync`

**Comment by Zhigang27** [comment]
我在您说的两个地方增加了KAYAKING_TITLE了，运行了Run_data_sync之后，Publish_Github_Pages这个运行报错了。刷新了一下页面，KAYAKING的还是没进去。有空的时候能再帮忙看看吗？

**Comment by ben-29** [comment]
@Zhigang27 我试了下你附件的gpx数据，是文件编码问题，我修改了代码，你点击你仓库的 `Sync fork` 同步最新的代码试试， `Kayaking` 类型也加上了，同步之后应该能直接出来，有问题再反馈 :)

**Comment by Zhigang27** [comment]
我尝试了Sync Fork，然后在garmin_sync.py 里GET_ALL = True，再执行一次，但似乎10月4日的KAYAKING被跟与当天的两条骑车给合并到一起去了。相同的情况出现在10月23日，我的一条半马和之后的骑车也被合并了。见附件两个图片。
![IMG_0542](https://user-images.githubusercontent.com/118618521/202998631-9c76c173-4445-4e77-9a53-0377d24ffb28.PNG)
![IMG_AA54D24489A8-1](https://user-images.githubusercontent.com/118618521/202998767-eead7a54-d3a7-40e1-8b0a-c19f1b0b20f4.jpeg)

其实吧，我的皮划艇一共也就2次（10月4号和9月25号），只是从Running Page转过来试试你这个Workout之后，觉得很喜欢，就想自己试试能不能增加皮划艇，并识别出来。但我自己并不会代码，没搞成。我觉得我们可以保持沟通，尝试看看怎么把这个Workout弄得更完善（若有兴趣，可加我微信：18602153036）。也非常感谢您的耐心，感谢你的修改，为喜欢捣鼓数据的跑友提供了这么赞的程序。）

还有一个问题，mapbox我这里显示的都是英文，我搜索到一个帖子：https://blog.csdn.net/qq_27816785/article/details/123547437。但看不懂，自己完全不会代码。如果后续有空，能改进去，就太棒了。

**Comment by ben-29** [comment]
@Zhigang27 
1、原逻辑会合并两个1小时内的轨迹，没有考虑类型，感谢提醒，等有空我改下
2、mapbox显示英文问题也等我有空再看下
哈哈，我看你跑的大公鸡很有趣啊，已加，一起交流🤝(我修改把隐私信息删了)

**Comment by ben-29** [comment]
@Zhigang27 第一个问题你再`Sync fork`后 跑一下看看有没修复？

**Comment by Zhigang27** [comment]
已经修复啦，感谢，感谢

**Comment by ben-29** [comment]
问题2已修复
