### ISSUE TITLE
地图缩放彩蛋能显示中文运动类型吗?

### ISSUE THREAD

**Issue by urcsky** [ben-29/workouts_page#6]
你好，能向原作者那样显示中文的运动类型吗？
![Snipaste_2022-11-22_01-31-14](https://user-images.githubusercontent.com/116236078/203122343-95fbe778-3901-483c-bad6-29cbcb3b5391.png)
![Snipaste_2022-11-22_01-31-30](https://user-images.githubusercontent.com/116236078/203122416-96b05207-b684-4ac8-8d32-832b2acdb7cf.png)

**Comment by ben-29** [comment]
原repo里面涉及了三个：跑步子类型、数量、单位`Runs`
workouts有：运动类型、数量。
字段还有有些差别
你能把你的需求，举个例子 附上吗？
是像这样吗：
```
771 跑步
103 骑行
```

**Comment by urcsky** [comment]
是的就是像你描述的那样
跑步 771 runs
骑行 103 rides

**Comment by ben-29** [comment]
可以，等我有时间了改一下

**Comment by urcsky** [comment]
非常感谢！

**Comment by ben-29** [comment]
@urcsky 改了，可以拉最新代码试试
