### ISSUE TITLE
骑行数据的话用那个app？

### ISSUE THREAD

**Issue by MQ-0707** [ben-29/workouts_page#7]
大佬，骑行的话支持那个app

**Comment by ben-29** [comment]
在原项目的基础上 
https://github.com/yihong0618/running_page/blob/master/README-CN.md#%E6%94%AF%E6%8C%81
支持了 行者app

 一般用garmin/strava多一点，可以自动同步

**Comment by MQ-0707** [comment]
就是跟原作者的跑步数据用同一个app，这样拉取的时候数据怎么区分跑步和骑行和徒步，这几个的数据是怎么区分的？> 在原项目的基础上 
> 
> https://github.com/yihong0618/running_page/blob/master/README-CN.md#%E6%94%AF%E6%8C%81
> 
> 支持了 行者app
> 
> 
> 
>  一般用garmin/strava多一点，可以自动同步

**Comment by MQ-0707** [comment]
大佬，项目部署自己阿里云服务器上的话，需要怎么部署。

**Comment by ben-29** [comment]
在服务器和本地部署流程基本一样
参考 https://github.com/yihong0618/running_page/blob/master/README-CN.md#%E5%AE%89%E8%A3%85%E5%8F%8A%E6%B5%8B%E8%AF%95-node--16-python--38

最后 build + serve
```
pnpm build
pnpm serve --port 80
```

**Comment by MQ-0707** [comment]
阿里云部署的是不是就不能用github的actions+vercel实现动态更新数据，实现vercel部署的项目就是生成的连接访问速度太慢了，大佬你是怎么部署的，你的项目域名怎么绑定到自己的域名的

**Comment by ben-29** [comment]
1. 写个 cron 任务定时执行，也能实现定时更新
2. 要在 vecel 绑定自己的域名，首先配置域名的 dns 映射，加上一条 CNAME 记录，指向 cname.vercel-dns.com 。然后在 vecel 的 domains 里，添加对应的网址即可
![image](https://github.com/ben-29/workouts_page/assets/6956444/8f629f23-071e-46c5-9902-049604029ee9)

**Comment by MQ-0707** [comment]
大佬，原来项目的那个actions可以用吗？定时任务这在哪里？用py 写吗？可以给个例子吗？py 不是很会这个语言，🌺🌺🌺😊> 1. 写个 cron 任务定时执行，也能实现定时更新
> 
> 2. 要在 vecel 绑定自己的域名，首先配置域名的 dns 映射，加上一条 CNAME 记录，指向 cname.vercel-dns.com 。然后在 vecel 的 domains 里，添加对应的网址即可
> 
> ![image](https://github.com/ben-29/workouts_page/assets/6956444/8f629f23-071e-46c5-9902-049604029ee9)
> 
>

**Comment by ben-29** [comment]
自己部署会比较麻烦，你需要知道基本的 crontab 知识。
action 里要执行的相关执行，逐一加到 crontab 里设定每日同步即可
假设你用的是 strava， 就要用执行这个：
https://github.com/ben-29/workouts_page/blob/b0eb19c83d99c1ddbd819112519b93b9bd64b67f/.github/workflows/run_data_sync.yml#L103
以及这部分：
https://github.com/ben-29/workouts_page/blob/b0eb19c83d99c1ddbd819112519b93b9bd64b67f/.github/workflows/run_data_sync.yml#L178

或者最简单的，等 github action执行完后，在本地添加用 cron 任务(如明天九点定时)，直接 pull 最新代码
