### ISSUE TITLE
咕咚数据获取失败

### ISSUE THREAD

**Issue by arthurfsy** [ben-29/workouts_page#8]
在运行以下代码后，出现错误提示，求教如何解决
`python scripts/codoon_sync.py 1333XXXX XXXXX`

错误提示：
`panic: unknown time zone Pacific/Kanton

goroutine 1 [running]:
main.init.0()
        /home/runner/work/tzf/tzf/python/tzfpy/main.go:21 +0x66
Aborted (core dumped)`

**Comment by ben-29** [comment]
看到在上游处理了，先关了
