### ISSUE TITLE
请教下打开页面的时候怎么默认展示最新年份地图及运动记录，而不是默认Total地图及Total总结

### ISSUE THREAD

**Issue by koobai** [ben-29/workouts_page#9]
请教下打开页面的时候怎么默认展示最新年份地图及运动记录，而不是默认Total地图及Total总结。跟原版的展示方式一样。感谢

**Comment by ben-29** [comment]
https://github.com/ben-29/workouts_page/blob/b78fbc8179c8da1c93b8ba81e8c7abef6b717aa6/src/pages/index.jsx#L28 
`'Total'` -> `thisYear`

**Comment by koobai** [comment]
收到，非常感谢

**Comment by koobai** [comment]
再请教下，自定义域名之后，地图就显示不出来，应该怎么修改修改下。
看生成的静态页面，调用的JS路径，多了个仓库名称。不知道是不是因为这原因导致自定义域名无法显示地图。想去掉路径仓库名称试试，但不知道哪去～

**Comment by ben-29** [comment]
参考 https://github.com/yihong0618/running_page/blob/master/README-CN.md#serverrecommend-vercel -> `部署到 GitHub Pages` -> 2.iii 修改，设置 `fqdn` 并取消注释

**Comment by koobai** [comment]
感谢，之前也是参考的这个，修改fqdn为自己自定义的域名，并取消前面//的注释，发现没用。会导致地图不显示

**Comment by koobai** [comment]
<img width="726" alt="image" src="https://user-images.githubusercontent.com/50470569/230520498-9d8f4e88-ec0e-4389-8900-b44f80b775eb.png">
改完之后就跟前面说的一样，多了个仓库名路径，导致这些JS都打不开～

**Comment by koobai** [comment]
已经搞定，需要将
pathPrefix: process.env.PATH_PREFIX || '/',
改为：pathPrefix: '',

感谢~
